### ISSUE TITLE
[PATCH] Fix doc/man/Makefile

### ISSUE THREAD

**Issue by hartwork** [wiki2beamer/wiki2beamer#41]
Hi!

While [bumping wiki2beamer to 0.10.0 for Gentoo](https://github.com/gentoo/gentoo/commit/815ec15d3681ffc60008f889f543cda282639df8), I noticed that `doc/man/Makefile` has broken dependencies and also calls out to `man(1)` while building the man page. I have a [patch ready for `git am`](https://raw.githubusercontent.com/gentoo/gentoo/815ec15d3681ffc60008f889f543cda282639df8/app-text/wiki2beamer/files/wiki2beamer-0.10.0-doc-man-makefile.patch). If you need a pull request instead, please let me know.

Best, Sebastian

**Comment by esc** [comment]
@hartwork thanks for the fix and good to see you again, at least virtually! Pull-request isn't required, I have applied the patch to master as a0492486408ab50bc00de414b6a8ae6fcd8fca82.

Do you need a new release?

**Comment by hartwork** [comment]
Excellent, thanks!

No need for a sooner release than regular as far as I'm concerned, but thanks!

**Comment by hartwork** [comment]
Should we close the ticket?

**Comment by esc** [comment]
Sure
